name: Lotto Fetch & Build Data

on:
  workflow_dispatch: {} # Actions 탭에서 "Run workflow" 버튼
  push:
    paths:
      - "scripts/fetch_all.js"

permissions:
  contents: write

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm i node-fetch@3

      - name: Fetch all rounds
        run: node scripts/fetch_all.js

      - name: Commit & push draws.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/draws.json
          git commit -m "data: update draws.json (full backfill)" || echo "no changes"
          git push

          